### ISSUE TITLE
Implement header/footer for IDE component

### ISSUE THREAD

**Issue by mambetakunova** [devkurultay/kodjaz_frontend#34]
![image](https://user-images.githubusercontent.com/6377605/211159572-aea89290-d814-4924-97f4-bc9930229dea.png)
![image](https://user-images.githubusercontent.com/6377605/211159588-b99d9344-283d-49da-ade6-d10e9977879b.png)

**Comment by janaratolonbaeva** [comment]
This issue completed in the [33-implement-description-component-lectureinstructionhint](url) issue without responsive.
